// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ts22082/logging-service/templates/components"
import "github.com/ts22082/logging-service/utils/project_types"

func AdminProjectPage(apiKeys []project_types.ApiKey) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"stylesheet\" href=\"/static/dist/styles/reset.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/utils.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/styles.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/modal.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/containers.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/buttons.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.UserNav("Oggee", "dashboard").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div popover id=\"delete-key-popover\" class=\"key_modal\"><h1 class=\"mb-20\">Delete this key?</h1><p class=\"mb-20\">This is not reversible, this api key will no longer be able to make requests to the system.</p><div><button id=\"cancelDeleteKey\" class=\"btn btn__normal\">Cancel</button> <button id=\"confirmDeleteBtn\" class=\"btn btn__caution\">Delete</button></div></div><dialog class=\"key_modal\" id=\"showKeyModal\"><h1 class=\"mb-20\">This is your api key</h1><p class=\"mb-20\">Copy the key and save it somewhere safe, this will not be shows again.</p><code id=\"keyText\"></code><div class=\"mt-20\"><button id=\"closeKeyModalBtn\" class=\"btn btn__normal\">Close</button></div></dialog><section class=\"jumbo\"><h1>Project Admin Page</h1><p>Here, you can add members and create API keys for the project.</p></section><div class=\"projectsMainContainer\"><section class=\"addMemberSection\"><form><input class=\"text__input\" placeholder=\"Enter email address here\"> <button class=\"btn btn__primary\">Add Project Member</button></form><table class=\"projectsTable\"><thead><tr><th>Email</th><th>Status</th><th>Actions</th></tr></thead> <tbody><tr><td>wow</td><td>wow</td><td>wow</td></tr></tbody></table></section><section class=\"addKeySection\"><form id=\"createApiKey\"><button id=\"submitKeyBtn\" type=\"submit\" class=\"btn btn__primary\">Create API Key</button></form><table class=\"projectsTable\"><thead><tr><th>Key</th><th>Requests</th><th>Actions</th></tr></thead> <tbody id=\"keyTable\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, apiKey := range apiKeys {
			trId := "tr-" + apiKey.Id.Hex()
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<tr id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(trId)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/AdminProjectPage.templ`, Line: 79, Col: 21}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><td>...")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(apiKey.Token)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/AdminProjectPage.templ`, Line: 80, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</td><td>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(apiKey.Count)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/AdminProjectPage.templ`, Line: 81, Col: 27}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</td><td><button class=\"delete__link\" data-id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(apiKey.Id.Hex())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/AdminProjectPage.templ`, Line: 83, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\">Delete </button></td></tr>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</tbody></table></section></div><script type=\"module\" src=\"/static/dist/scripts/admin_project_page.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
