// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ts22082/logging-service/templates/components"

const card1Title = "Instant Insights, Zero Guesswork"
const card1Desc = "Get real-time analytics and critical alerts from your app logs so your team can focus on what matters most."

const card2Title = "Proactive Issue Detection"
const card2Desc = "Let AI spot bugs, anomalies, and potential bottlenecks before they impact your users."

const card3Title = "Tailored Metrics & Visualizations"
const card3Desc = "Customize dashboards and reports to match your team's unique needs and see the data that drives your app's success."

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"stylesheet\" href=\"/static/dist/styles/reset.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/styles.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/containers.css\"><link rel=\"stylesheet\" href=\"/static/dist/styles/buttons.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Nav("Oggee", "home").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section class=\"jumbo\"><h1>Unlock Intelligent Insights From Your App Logs</h1><p>AI-powered analytics and critical information to drive better product decisions.</p><div id=\"home_btn_group\" class=\"home_btn_group\"><button id=\"learnMoreBtn\" class=\"btn btn__primary\">Learn More</button> <button id=\"logInBtn\" class=\"btn btn__normal\">Log In</button></div></section><div class=\"landing__card__section\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Card(card1Title, card1Desc).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Card(card2Title, card2Desc).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Card(card3Title, card3Desc).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><section class=\"jumbo\"><h1>Go Beyond the Surface To See What Really Matters</h1><p>Access the analytics and intelligence you need to make informed decisions every step of the way.</p><div class=\"home_btn_group\"><button id=\"createAccountBtn\" class=\"btn btn__primary\">Create An Account</button></div></section><script type=\"module\" src=\"/static/dist/scripts/home_page.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
